// ============================================================
// Lista maestra de campos del formulario + etiquetas legibles.
// Se usa tanto para enviar los datos a la planilla de Google Sheets
// (orden de columnas) como para mostrarlos en el panel de gestión.
// ============================================================

const ALL_FIELD_NAMES = [
  // Titular
  "tit_nombre", "tit_fecha_solicitud", "tit_ci", "tit_monto_solicitado", "tit_monto_concedido",
  "tit_nacionalidad", "tit_sexo", "tit_fecha_nac", "tit_vivienda", "tit_vivienda_otra",
  "tit_estado_civil", "tit_celular", "tit_email", "meta_sucursal", "meta_seccion", "meta_captador",
  // Domicilio
  "dom_direccion", "dom_barrio", "dom_ciudad", "dom_obs",
  // Laboral
  "lab_empresa", "lab_celular", "lab_direccion", "lab_tipo_empleo", "lab_tipo_empleo_otro",
  "lab_cargo", "lab_monto_ingreso", "lab_antiguedad",
  // Ingresos / egresos
  "ing_sueldo", "ing_sueldo_conyuge", "ing_jubilacion", "ing_otros", "ing_total",
  "egr_gastos_familiares", "egr_cuota_prestamos", "egr_alquiler", "egr_otros", "egr_total",
  // Referencias
  "refcom1_entidad", "refcom1_telefono", "refcom2_entidad", "refcom2_telefono",
  "refper1_nombre", "refper1_celular", "refper1_vinculo",
  "refper2_nombre", "refper2_celular", "refper2_vinculo",
  // Cónyuge / adicional
  "con_nombre", "con_nacionalidad", "con_ci", "con_sexo", "con_fecha_nac",
  "conlab_empresa", "conlab_celular", "conlab_direccion", "conlab_tipo_empleo", "conlab_tipo_empleo_otro",
  "conlab_cargo", "conlab_monto_ingreso", "conlab_antiguedad",
  // Registro de firmas
  "firma_nombres", "firma_apellidos",
  // Tarjeta
  "card_numero", "card_linea_credito", "card_costo_emision", "card_costo_cuota_anual",
  "card_costo_renovacion", "card_interes_compensatorio", "card_interes_moratorio",
  "card_interes_punitorio", "card_gestion_recupero",
  // Seguro
  "seg_sucursal", "seg_poliza", "seg_asegurado", "seg_documento", "seg_domicilio", "seg_localidad",
  "seg_emision", "seg_vigencia_desde", "seg_vigencia_hasta", "seg_plazo", "seg_capital",
  // Campos nuevos, agregados al final para no romper el orden de columnas ya existentes
  "egr_otros_detalle", "ing_otros_detalle",
];

const FIELD_LABELS = {
  tit_nombre: "Nombres y Apellidos (Titular)",
  tit_fecha_solicitud: "Fecha de la solicitud",
  tit_ci: "Número Doc. Identidad",
  tit_monto_solicitado: "Monto Solicitado",
  tit_monto_concedido: "Monto Concedido",
  tit_nacionalidad: "Nacionalidad",
  tit_sexo: "Sexo",
  tit_fecha_nac: "Fecha de Nacimiento",
  tit_vivienda: "Vivienda",
  tit_vivienda_otra: "Vivienda (especificar)",
  tit_estado_civil: "Estado Civil",
  tit_celular: "Número de Celular",
  tit_email: "Correo Electrónico",
  meta_sucursal: "Sucursal",
  meta_seccion: "Sección",
  meta_captador: "Captador",
  dom_direccion: "Dirección",
  dom_barrio: "Barrio",
  dom_ciudad: "Ciudad",
  dom_obs: "Obs. domicilio",
  lab_empresa: "Empresa",
  lab_celular: "Celular laboral",
  lab_direccion: "Dirección Laboral",
  lab_tipo_empleo: "Tipo de empleo",
  lab_tipo_empleo_otro: "Tipo de empleo (especificar)",
  lab_cargo: "Cargo",
  lab_monto_ingreso: "Monto de Ingreso",
  lab_antiguedad: "Antigüedad",
  ing_sueldo: "Sueldo",
  ing_sueldo_conyuge: "Sueldo Cónyuge",
  ing_jubilacion: "Jubilación",
  ing_otros: "Otros ingresos",
  ing_total: "TOTAL INGRESOS",
  egr_gastos_familiares: "Gastos familiares",
  egr_cuota_prestamos: "Cuota de préstamos",
  egr_alquiler: "Alquiler pagado",
  egr_otros: "Otros egresos",
  egr_total: "TOTAL EGRESOS",
  refcom1_entidad: "Ref. Comercial 1 - Entidad",
  refcom1_telefono: "Ref. Comercial 1 - Teléfono",
  refcom2_entidad: "Ref. Comercial 2 - Entidad",
  refcom2_telefono: "Ref. Comercial 2 - Teléfono",
  refper1_nombre: "Ref. Personal 1 - Nombre",
  refper1_celular: "Ref. Personal 1 - Celular",
  refper1_vinculo: "Ref. Personal 1 - Vínculo",
  refper2_nombre: "Ref. Personal 2 - Nombre",
  refper2_celular: "Ref. Personal 2 - Celular",
  refper2_vinculo: "Ref. Personal 2 - Vínculo",
  con_nombre: "Nombres y Apellidos (Cónyuge/Adicional)",
  con_nacionalidad: "Nacionalidad (Cónyuge)",
  con_ci: "Doc. Identidad (Cónyuge)",
  con_sexo: "Sexo (Cónyuge)",
  con_fecha_nac: "Fecha de Nacimiento (Cónyuge)",
  conlab_empresa: "Empresa (Cónyuge)",
  conlab_celular: "Celular laboral (Cónyuge)",
  conlab_direccion: "Dirección Laboral (Cónyuge)",
  conlab_tipo_empleo: "Tipo de empleo (Cónyuge)",
  conlab_tipo_empleo_otro: "Tipo de empleo (Cónyuge, especificar)",
  conlab_cargo: "Cargo (Cónyuge)",
  conlab_monto_ingreso: "Monto de Ingreso (Cónyuge)",
  conlab_antiguedad: "Antigüedad (Cónyuge)",
  firma_nombres: "Nombres (Registro de Firmas)",
  firma_apellidos: "Apellidos (Registro de Firmas)",
  card_numero: "Nro. de Tarjeta",
  card_linea_credito: "Línea de Crédito Gs.",
  card_costo_emision: "Costo de Emisión",
  card_costo_cuota_anual: "Costo de Cuota anual/Renovación",
  card_costo_renovacion: "Costo de Renovación",
  card_interes_compensatorio: "Interés compensatorio (%)",
  card_interes_moratorio: "Interés Moratorio (%)",
  card_interes_punitorio: "Interés Punitorio (%)",
  card_gestion_recupero: "Gestión de Recupero de Crédito en Mora",
  seg_sucursal: "Seguro - Sucursal",
  seg_poliza: "Seguro - Póliza/Endorso N°",
  seg_asegurado: "Seguro - Asegurado",
  seg_documento: "Seguro - Documento",
  seg_domicilio: "Seguro - Domicilio",
  seg_localidad: "Seguro - Localidad",
  seg_emision: "Seguro - Emisión",
  seg_vigencia_desde: "Seguro - Vigencia desde",
  seg_vigencia_hasta: "Seguro - Vigencia hasta",
  seg_plazo: "Seguro - Plazo",
  seg_capital: "Seguro - Capital Asegurado",
  egr_otros_detalle: "Otros egresos (detalle)",
  ing_otros_detalle: "Otros ingresos (detalle)",
};

// Grupos usados para armar la vista de detalle del panel de gestión.
const FIELD_GROUPS = [
  { title: "Datos del Titular", fields: ["tit_nombre","tit_fecha_solicitud","tit_ci","tit_monto_solicitado","tit_monto_concedido","tit_nacionalidad","tit_sexo","tit_fecha_nac","tit_vivienda","tit_vivienda_otra","tit_estado_civil","tit_celular","tit_email","meta_sucursal","meta_seccion","meta_captador"] },
  { title: "Domicilio Particular", fields: ["dom_direccion","dom_barrio","dom_ciudad","dom_obs"] },
  { title: "Datos Laborales", fields: ["lab_empresa","lab_celular","lab_direccion","lab_tipo_empleo","lab_tipo_empleo_otro","lab_cargo","lab_monto_ingreso","lab_antiguedad"] },
  { title: "Ingresos y Egresos", fields: ["ing_sueldo","ing_sueldo_conyuge","ing_jubilacion","ing_otros","ing_otros_detalle","ing_total","egr_gastos_familiares","egr_cuota_prestamos","egr_alquiler","egr_otros","egr_otros_detalle","egr_total"] },
  { title: "Referencias", fields: ["refcom1_entidad","refcom1_telefono","refcom2_entidad","refcom2_telefono","refper1_nombre","refper1_celular","refper1_vinculo","refper2_nombre","refper2_celular","refper2_vinculo"] },
  { title: "Cónyuge / Adicional", fields: ["con_nombre","con_nacionalidad","con_ci","con_sexo","con_fecha_nac","conlab_empresa","conlab_celular","conlab_direccion","conlab_tipo_empleo","conlab_tipo_empleo_otro","conlab_cargo","conlab_monto_ingreso","conlab_antiguedad"] },
  { title: "Registro de Firmas", fields: ["firma_nombres","firma_apellidos"] },
  { title: "Datos de Tarjeta", fields: ["card_numero","card_linea_credito","card_costo_emision","card_costo_cuota_anual","card_costo_renovacion","card_interes_compensatorio","card_interes_moratorio","card_interes_punitorio","card_gestion_recupero"] },
  { title: "Seguro Crediticio", fields: ["seg_sucursal","seg_poliza","seg_asegurado","seg_documento","seg_domicilio","seg_localidad","seg_emision","seg_vigencia_desde","seg_vigencia_hasta","seg_plazo","seg_capital"] },
];
